### ISSUE TITLE
Research on community best-practices

### ISSUE THREAD

**Issue by troggy** [leapdao/docs#11]
# Resources
## README
https://github.com/RichardLitt/standard-readme — spec, linter and generator
https://github.com/noffle/art-of-readme

## Contribution
http://scottchacon.com/2011/08/31/github-flow.html

## Ethics
https://www.w3.org/Consortium/cepc/

## Everything
https://github.com/davidbgk/open-source-template/

**Comment by johannbarbie** [comment]
don't know what to do with this. not a defined issue, but relevant for good docs. 🤷‍♂️
