### ISSUE TITLE
How to migrate a dApp to Plasma - blog post / doc 

### ISSUE THREAD

**Issue by kohola71** [leapdao/docs#17]
## Scope
* describe the steps necessary to migrate a dApp from layer 1 to layer 2 
* explain how to modify the storage of the contract / how to deploy the contract 
* how to use the same tools that devs know from the mainnet to talk to the contract (send transactions) 

## Deliverables
* blog post copy / updated docs 

## Gain for the project
* ecosystem developer education 

## Roles: 
bounty gardener: @kohola71  / 10%  
bounty worker: name / share 
bounty reviewer: @johannbarbie  / share 

Size - M (8 hrs)

**Comment by johannbarbie** [comment]
bounty timed out
