### ISSUE TITLE
Typo on a "Validators » Leap Network Introduction"

### ISSUE THREAD

**Issue by troggy** [leapdao/docs#47]
![image](https://user-images.githubusercontent.com/163447/68677249-d1a3c800-056c-11ea-9585-dc5b9fb5b91d.png)

**Comment by troggy** [comment]
@simonweniger do you have a source of this picture (SVG or something) ?

**Comment by simonweniger** [comment]
yeah currently did it as a png but i also can import it as SVG -- here you can find all the designs and export them:  https://www.figma.com/file/h5lsuaMvYEXQ9cJTDH08jQ/LeapDAO-Graphics?node-id=0%3A1   **im going to change the spelling mistake now**  @troggy
