### ISSUE TITLE
Update/Clarify Validator Document 

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/docs#58]
## Scope
- Gather info from bugs / error messages / dead ends 
- Add and update new info
- Rewrite passages that are unclear
- check github [descriptions](https://github.com/leapdao/leap-node) and update or simple redirect them to docs.leapdao.org

## Deliverables
Adding and rewriting text on "How to set up a node" in the existing [document](https://docs.leapdao.org/connect/) 

## Gain for the project
Set foundation for testing environment to decentralize the Leap Network.

## Roles
bounty gardener: @MaxKuck  / 10%
bounty worker: @MaxKuck / 40%
worker @troggy  / 25%
bounty reviewer: @johannbarbie / 25%

**Comment by MaxKuck** [comment]
Bounty Size S

**Comment by troggy** [comment]
@MaxKuck maybe you meant @johannbarbie is the worker? I see he posted the actual change here https://github.com/leapdao/docs/pull/59

**Comment by troggy** [comment]
@MaxKuck maybe post a comment in a spirit of freshly adopted "Takeover" policy? 😆

**Comment by MaxKuck** [comment]
> @MaxKuck maybe you meant @johannbarbie is the worker, not me? I see he made the actual change here #59

your share is legit, you did some help in this thread and in general: https://leapdao.slack.com/archives/CFKUNHHC7/p1578235387007500?thread_ts=1578066112.003400&cid=CFKUNHHC7
